language: c

env:
    CTEST_OUTPUT_ON_FAILURE=True

jobs:
  include:
    - stage: compile
      before_install:
        - sudo apt-get install -y libblas-dev liblapack-dev gfortran
      script:
        - ./configure.sh --debug && cd build-debug/
        - make
        - make install
        - make test

    - stage: documentation
      before_install:
        - sudo apt-get install -y doxygen graphviz
      script:
        - .ci/travis-deploy.sh
