!> Tests that derived constants have sane value.
program libgrasp_asfs_read
   use, intrinsic :: iso_fortran_env, only: real64
   use grasptest, only: test_isequal, abstol, getenv_allocating
   use grasp_datafiles, only: asfs_t, asfs_read, asfs_write
   implicit none
   integer, parameter :: dp = real64
   ! Local variables
   logical :: success = .true.
   type(asfs_t) :: asfs
   logical status
   character(:), allocatable :: srcdir
   integer :: k

   status = getenv_allocating('GRASP_ASFS_SOURCE', srcdir)
   if (.not. status) then
      print *, "Failed to get GRASP_ASFS_SOURCE environment variable"
      error stop
   endif

   ! Check error handling. This file should not exist.
   status = asfs_read('/foo/bar/baz', asfs)
   call test_isequal(success, 'asfs_read:error', status, .false.)
   ! This file exists, but should contain rubbish
   status = asfs_read(srcdir//"/rubbish", asfs)
   call test_isequal(success, 'asfs_read:rubbish', status, .false.)

   ! Read in a mixing file generated by RCI
   ! We have 27 / 27 / 46 CSFs in each block, but only calculate 7 / 1 / 46 eigenvalues.
   status = asfs_read(srcdir//"/teststate.cm", asfs)
   call test_isequal(success, 'teststate', status, .true.)
   call test_isequal(success, 'teststate:nlocks', asfs%nblocks, 3)
   call test_isequal(success, 'teststate:size(blocks)', size(asfs%blocks), asfs%nblocks)
   call test_isequal(success, 'teststate:NCFTOT', asfs%NCFTOT, 21+27+46)
   ! Number of orbitals
   call test_isequal(success, 'teststate:NW', asfs%NW, 37)
   ! NVECTOT appears to be total number of ASFs
   call test_isequal(success, 'teststate:NVECTOT', asfs%NVECTOT, 7+1+46)
   ! Number of electrons
   call test_isequal(success, 'teststate:NELEC', asfs%NELEC, 88)
   ! Total number of ASF coefficients across all blocks
   call test_isequal(success, 'teststate:NVECSIZ', asfs%NVECSIZ,  21*7 + 27*1 + 46*46)
   ! Data in each block
   ! Block #1
   call test_isequal(success, 'teststate:1:nstates', asfs%blocks(1)%nstates, 7)
   call test_isequal(success, 'teststate:1:ncsfs', asfs%blocks(1)%ncsfs, 21)
   call test_isequal(success, 'teststate:1:size(ivec)', size(asfs%blocks(1)%ivec), 7)
   call test_isequal(success, 'teststate:1:size(eval)', size(asfs%blocks(1)%eval), 7)
   ! Block #2
   call test_isequal(success, 'teststate:2:nstates', asfs%blocks(2)%nstates, 1)
   call test_isequal(success, 'teststate:2:ncsfs', asfs%blocks(2)%ncsfs, 27)
   call test_isequal(success, 'teststate:2:size(ivec)', size(asfs%blocks(2)%ivec), 1)
   call test_isequal(success, 'teststate:2:size(eval)', size(asfs%blocks(2)%eval), 1)
   ! Block #3
   call test_isequal(success, 'teststate:3:nstates', asfs%blocks(3)%nstates, 46)
   call test_isequal(success, 'teststate:3:ncsfs', asfs%blocks(3)%ncsfs, 46)
   call test_isequal(success, 'teststate:3:size(ivec)', size(asfs%blocks(3)%ivec), 46)
   call test_isequal(success, 'teststate:3:size(eval)', size(asfs%blocks(3)%eval), 46)

   ! Write out the data that was read in:
   status = asfs_write(asfs, "teststate.m")
   call test_isequal(success, 'asfs_write', status, .true.)
   ! Let's also try a failed write (no permissions)
   status = asfs_write(asfs, "/foo/bar/baz/teststate.m")
   call test_isequal(success, 'asfs_write:fail', status, .false.)

   if (.not. success) then
      print *, "libgrasp_isodata: Tests failed."
      stop 1
   end if

end program libgrasp_asfs_read
